#! /usr/bin/env bash

echo "Extracting spikes..."
python extract_spike_data.py

echo "Extracting ethogram..."
source get_etho

echo "Extracting presentations..."
source get_presentations

echo "Merging spikes with presentations..."
python merge_counts_with_presentations.py